export const jsonOver5KB = {
    records: [
        {
            id: 1,
            name: "Alice",
            email: "alice@example.com",
            role: "admin",
            meta: {
                login: "2025-12-23T12:00:00Z",
                prefs: { theme: "dark", lang: ["en", "tr", "es"] },
            },
        },
        {
            id: 2,
            name: "Bob",
            email: "bob@example.com",
            role: "user",
            meta: {
                login: "2025-12-22T09:30:00Z",
                prefs: { theme: "light", lang: ["en", "fr"] },
            },
        },
        {
            id: 3,
            name: "Charlie",
            email: "charlie@example.com",
            role: "editor",
            meta: {
                login: "2025-12-21T18:45:00Z",
                prefs: { theme: "dark", lang: ["en", "de"] },
            },
        },
        {
            id: 4,
            name: "David",
            email: "david@example.com",
            role: "user",
            meta: {
                login: "2025-12-20T14:20:00Z",
                prefs: { theme: "light", lang: ["en", "it"] },
            },
        },
        {
            id: 5,
            name: "Eve",
            email: "eve@example.com",
            role: "admin",
            meta: {
                login: "2025-12-19T10:10:00Z",
                prefs: { theme: "dark", lang: ["en", "ja"] },
            },
        },
        {
            id: 6,
            name: "Frank",
            email: "frank@example.com",
            role: "user",
            meta: {
                login: "2025-12-18T16:55:00Z",
                prefs: { theme: "light", lang: ["en", "ko"] },
            },
        },
        {
            id: 7,
            name: "Grace",
            email: "grace@example.com",
            role: "editor",
            meta: {
                login: "2025-12-17T11:30:00Z",
                prefs: { theme: "dark", lang: ["en", "zh"] },
            },
        },
        {
            id: 8,
            name: "Hank",
            email: "hank@example.com",
            role: "user",
            meta: {
                login: "2025-12-16T08:15:00Z",
                prefs: { theme: "light", lang: ["en", "ru"] },
            },
        },
        {
            id: 9,
            name: "Ivy",
            email: "ivy@example.com",
            role: "admin",
            meta: {
                login: "2025-12-15T19:45:00Z",
                prefs: { theme: "dark", lang: ["en", "ar"] },
            },
        },
        {
            id: 10,
            name: "Jack",
            email: "jack@example.com",
            role: "user",
            meta: {
                login: "2025-12-14T07:50:00Z",
                prefs: { theme: "light", lang: ["en", "pt"] },
            },
        },
        {
            id: 11,
            name: "Kathy",
            email: "kathy@example.com",
            role: "user",
            meta: {
                login: "2025-12-13T12:10:00Z",
                prefs: { theme: "dark", lang: ["en", "sv"] },
            },
        },
        {
            id: 12,
            name: "Leo",
            email: "leo@example.com",
            role: "editor",
            meta: {
                login: "2025-12-12T15:30:00Z",
                prefs: { theme: "light", lang: ["en", "no"] },
            },
        },
        {
            id: 13,
            name: "Mona",
            email: "mona@example.com",
            role: "user",
            meta: {
                login: "2025-12-11T18:20:00Z",
                prefs: { theme: "dark", lang: ["en", "fi"] },
            },
        },
        {
            id: 14,
            name: "Nick",
            email: "nick@example.com",
            role: "admin",
            meta: {
                login: "2025-12-10T20:10:00Z",
                prefs: { theme: "light", lang: ["en", "da"] },
            },
        },
        {
            id: 15,
            name: "Olivia",
            email: "olivia@example.com",
            role: "user",
            meta: {
                login: "2025-12-09T09:40:00Z",
                prefs: { theme: "dark", lang: ["en", "is"] },
            },
        },
        {
            id: 16,
            name: "Paul",
            email: "paul@example.com",
            role: "user",
            meta: {
                login: "2025-12-08T13:25:00Z",
                prefs: { theme: "light", lang: ["en", "nl"] },
            },
        },
        {
            id: 17,
            name: "Quincy",
            email: "quincy@example.com",
            role: "editor",
            meta: {
                login: "2025-12-07T16:55:00Z",
                prefs: { theme: "dark", lang: ["en", "pl"] },
            },
        },
        {
            id: 18,
            name: "Rachel",
            email: "rachel@example.com",
            role: "user",
            meta: {
                login: "2025-12-06T19:35:00Z",
                prefs: { theme: "light", lang: ["en", "cs"] },
            },
        },
        {
            id: 19,
            name: "Steve",
            email: "steve@example.com",
            role: "admin",
            meta: {
                login: "2025-12-05T08:20:00Z",
                prefs: { theme: "dark", lang: ["en", "hu"] },
            },
        },
        {
            id: 20,
            name: "Tina",
            email: "tina@example.com",
            role: "user",
            meta: {
                login: "2025-12-04T12:10:00Z",
                prefs: { theme: "light", lang: ["en", "ro"] },
            },
        },
        {
            id: 21,
            name: "Uma",
            email: "uma@example.com",
            role: "user",
            meta: {
                login: "2025-12-03T14:00:00Z",
                prefs: { theme: "dark", lang: ["en", "sv"] },
            },
        },
        {
            id: 22,
            name: "Victor",
            email: "victor@example.com",
            role: "user",
            meta: {
                login: "2025-12-02T10:30:00Z",
                prefs: { theme: "light", lang: ["en", "bg"] },
            },
        },
        {
            id: 23,
            name: "Wendy",
            email: "wendy@example.com",
            role: "editor",
            meta: {
                login: "2025-12-01T17:15:00Z",
                prefs: { theme: "dark", lang: ["en", "sk"] },
            },
        },
        {
            id: 24,
            name: "Xavier",
            email: "xavier@example.com",
            role: "user",
            meta: {
                login: "2025-11-30T13:45:00Z",
                prefs: { theme: "light", lang: ["en", "sl"] },
            },
        },
        {
            id: 25,
            name: "Yara",
            email: "yara@example.com",
            role: "admin",
            meta: {
                login: "2025-11-29T09:20:00Z",
                prefs: { theme: "dark", lang: ["en", "hr"] },
            },
        },
        {
            id: 26,
            name: "Zoe",
            email: "zoe@example.com",
            role: "user",
            meta: {
                login: "2025-11-28T15:10:00Z",
                prefs: { theme: "light", lang: ["en", "sr"] },
            },
        },
        {
            id: 27,
            name: "Adam",
            email: "adam@example.com",
            role: "user",
            meta: {
                login: "2025-11-27T11:25:00Z",
                prefs: { theme: "dark", lang: ["en", "mk"] },
            },
        },
        {
            id: 28,
            name: "Beth",
            email: "beth@example.com",
            role: "editor",
            meta: {
                login: "2025-11-26T18:40:00Z",
                prefs: { theme: "light", lang: ["en", "sq"] },
            },
        },
        {
            id: 29,
            name: "Carl",
            email: "carl@example.com",
            role: "user",
            meta: {
                login: "2025-11-25T14:55:00Z",
                prefs: { theme: "dark", lang: ["en", "lv"] },
            },
        },
        {
            id: 30,
            name: "Dana",
            email: "dana@example.com",
            role: "admin",
            meta: {
                login: "2025-11-24T08:30:00Z",
                prefs: { theme: "light", lang: ["en", "lt"] },
            },
        },
        {
            id: 31,
            name: "Erik",
            email: "erik@example.com",
            role: "user",
            meta: {
                login: "2025-11-23T16:20:00Z",
                prefs: { theme: "dark", lang: ["en", "et"] },
            },
        },
        {
            id: 32,
            name: "Fiona",
            email: "fiona@example.com",
            role: "user",
            meta: {
                login: "2025-11-22T12:45:00Z",
                prefs: { theme: "light", lang: ["en", "mt"] },
            },
        },
        {
            id: 33,
            name: "Greg",
            email: "greg@example.com",
            role: "editor",
            meta: {
                login: "2025-11-21T19:10:00Z",
                prefs: { theme: "dark", lang: ["en", "cy"] },
            },
        },
        {
            id: 34,
            name: "Helen",
            email: "helen@example.com",
            role: "user",
            meta: {
                login: "2025-11-20T07:35:00Z",
                prefs: { theme: "light", lang: ["en", "ga"] },
            },
        },
        {
            id: 35,
            name: "Ian",
            email: "ian@example.com",
            role: "admin",
            meta: {
                login: "2025-11-19T13:50:00Z",
                prefs: { theme: "dark", lang: ["en", "eu"] },
            },
        },
        {
            id: 36,
            name: "Jane",
            email: "jane@example.com",
            role: "user",
            meta: {
                login: "2025-11-18T10:15:00Z",
                prefs: { theme: "light", lang: ["en", "ca"] },
            },
        },
        {
            id: 37,
            name: "Kyle",
            email: "kyle@example.com",
            role: "user",
            meta: {
                login: "2025-11-17T17:30:00Z",
                prefs: { theme: "dark", lang: ["en", "gl"] },
            },
        },
        {
            id: 38,
            name: "Luna",
            email: "luna@example.com",
            role: "editor",
            meta: {
                login: "2025-11-16T14:05:00Z",
                prefs: { theme: "light", lang: ["en", "ast"] },
            },
        },
        {
            id: 39,
            name: "Mark",
            email: "mark@example.com",
            role: "user",
            meta: {
                login: "2025-11-15T20:25:00Z",
                prefs: { theme: "dark", lang: ["en", "an"] },
            },
        },
        {
            id: 40,
            name: "Nina",
            email: "nina@example.com",
            role: "admin",
            meta: {
                login: "2025-11-14T06:40:00Z",
                prefs: { theme: "light", lang: ["en", "oc"] },
            },
        },
        {
            id: 41,
            name: "Oscar",
            email: "oscar@example.com",
            role: "user",
            meta: {
                login: "2025-11-13T12:55:00Z",
                prefs: { theme: "dark", lang: ["en", "co"] },
            },
        },
        {
            id: 42,
            name: "Penny",
            email: "penny@example.com",
            role: "user",
            meta: {
                login: "2025-11-12T09:10:00Z",
                prefs: { theme: "light", lang: ["en", "sc"] },
            },
        },
        {
            id: 43,
            name: "Quinn",
            email: "quinn@example.com",
            role: "editor",
            meta: {
                login: "2025-11-11T15:20:00Z",
                prefs: { theme: "dark", lang: ["en", "rm"] },
            },
        },
        {
            id: 44,
            name: "Rosa",
            email: "rosa@example.com",
            role: "user",
            meta: {
                login: "2025-11-10T18:45:00Z",
                prefs: { theme: "light", lang: ["en", "fur"] },
            },
        },
        {
            id: 45,
            name: "Sam",
            email: "sam@example.com",
            role: "admin",
            meta: {
                login: "2025-11-09T11:30:00Z",
                prefs: { theme: "dark", lang: ["en", "lad"] },
            },
        },
        {
            id: 46,
            name: "Tara",
            email: "tara@example.com",
            role: "user",
            meta: {
                login: "2025-11-08T16:15:00Z",
                prefs: { theme: "light", lang: ["en", "vec"] },
            },
        },
        {
            id: 47,
            name: "Ulric",
            email: "ulric@example.com",
            role: "user",
            meta: {
                login: "2025-11-07T08:50:00Z",
                prefs: { theme: "dark", lang: ["en", "lmo"] },
            },
        },
        {
            id: 48,
            name: "Vera",
            email: "vera@example.com",
            role: "editor",
            meta: {
                login: "2025-11-06T13:35:00Z",
                prefs: { theme: "light", lang: ["en", "pms"] },
            },
        },
        {
            id: 49,
            name: "Wade",
            email: "wade@example.com",
            role: "user",
            meta: {
                login: "2025-11-05T19:20:00Z",
                prefs: { theme: "dark", lang: ["en", "nap"] },
            },
        },
        {
            id: 50,
            name: "Zara",
            email: "zara@example.com",
            role: "admin",
            meta: {
                login: "2025-11-04T10:05:00Z",
                prefs: { theme: "light", lang: ["en", "scn"] },
            },
        },
    ],
};

export const jsonUnder5KB = {
    records: [
        {
            id: 1,
            name: "Alice",
            email: "alice@example.com",
            role: "admin",
            meta: {
                login: "2025-12-23T12:00:00Z",
                prefs: { theme: "dark", lang: ["en", "tr", "es"] },
            },
        },
        {
            id: 2,
            name: "Bob",
            email: "bob@example.com",
            role: "user",
            meta: { login: "2025-12-22T09:30:00Z", prefs: { theme: "light", lang: ["en", "fr"] } },
        },
        {
            id: 3,
            name: "Charlie",
            email: "charlie@example.com",
            role: "editor",
            meta: { login: "2025-12-21T18:45:00Z", prefs: { theme: "dark", lang: ["en", "de"] } },
        },
        {
            id: 4,
            name: "David",
            email: "david@example.com",
            role: "user",
            meta: { login: "2025-12-20T14:20:00Z", prefs: { theme: "light", lang: ["en", "it"] } },
        },
        {
            id: 5,
            name: "Eve",
            email: "eve@example.com",
            role: "admin",
            meta: { login: "2025-12-19T10:10:00Z", prefs: { theme: "dark", lang: ["en", "ja"] } },
        },
        {
            id: 6,
            name: "Frank",
            email: "frank@example.com",
            role: "user",
            meta: { login: "2025-12-18T16:55:00Z", prefs: { theme: "light", lang: ["en", "ko"] } },
        },
        {
            id: 7,
            name: "Grace",
            email: "grace@example.com",
            role: "editor",
            meta: { login: "2025-12-17T11:30:00Z", prefs: { theme: "dark", lang: ["en", "zh"] } },
        },
        {
            id: 8,
            name: "Hank",
            email: "hank@example.com",
            role: "user",
            meta: { login: "2025-12-16T08:15:00Z", prefs: { theme: "light", lang: ["en", "ru"] } },
        },
        {
            id: 9,
            name: "Ivy",
            email: "ivy@example.com",
            role: "admin",
            meta: { login: "2025-12-15T19:45:00Z", prefs: { theme: "dark", lang: ["en", "ar"] } },
        },
        {
            id: 10,
            name: "Jack",
            email: "jack@example.com",
            role: "user",
            meta: { login: "2025-12-14T07:50:00Z", prefs: { theme: "light", lang: ["en", "pt"] } },
        },
        {
            id: 11,
            name: "Kathy",
            email: "kathy@example.com",
            role: "user",
            meta: { login: "2025-12-13T12:10:00Z", prefs: { theme: "dark", lang: ["en", "sv"] } },
        },
        {
            id: 12,
            name: "Leo",
            email: "leo@example.com",
            role: "editor",
            meta: { login: "2025-12-12T15:30:00Z", prefs: { theme: "light", lang: ["en", "no"] } },
        },
        {
            id: 13,
            name: "Mona",
            email: "mona@example.com",
            role: "user",
            meta: { login: "2025-12-11T18:20:00Z", prefs: { theme: "dark", lang: ["en", "fi"] } },
        },
        {
            id: 14,
            name: "Nick",
            email: "nick@example.com",
            role: "admin",
            meta: { login: "2025-12-10T20:10:00Z", prefs: { theme: "light", lang: ["en", "da"] } },
        },
        {
            id: 15,
            name: "Olivia",
            email: "olivia@example.com",
            role: "user",
            meta: { login: "2025-12-09T09:40:00Z", prefs: { theme: "dark", lang: ["en", "is"] } },
        },
        {
            id: 16,
            name: "Paul",
            email: "paul@example.com",
            role: "user",
            meta: { login: "2025-12-08T13:25:00Z", prefs: { theme: "light", lang: ["en", "nl"] } },
        },
        {
            id: 17,
            name: "Quincy",
            email: "quincy@example.com",
            role: "editor",
            meta: { login: "2025-12-07T16:55:00Z", prefs: { theme: "dark", lang: ["en", "pl"] } },
        },
        {
            id: 18,
            name: "Rachel",
            email: "rachel@example.com",
            role: "user",
            meta: { login: "2025-12-06T19:35:00Z", prefs: { theme: "light", lang: ["en", "cs"] } },
        },
        {
            id: 19,
            name: "Steve",
            email: "steve@example.com",
            role: "admin",
            meta: { login: "2025-12-05T08:20:00Z", prefs: { theme: "dark", lang: ["en", "hu"] } },
        },
    ],
};
